# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: graal
      POSTGRES_PASSWORD: graal
      POSTGRES_DB: graal
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "graal"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres-db-volume:
